name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # Avoid running on draft PRs
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Use Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: npm i -g corepack@latest || corepack enable && corepack prepare pnpm@latest --activate
      - name: install
        run: pnpm install
      - name: lint
        run: pnpm run lint
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
